version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./.ssh
        target: /root/.ssh
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - default

networks:
  default:
    driver: bridge
